# Project 1:
## Diamonds Project.

### Uploading the Dataset.

In [1]:
# unzip the file.
from zipfile import ZipFile
with ZipFile("../data/Diamond.zip", "r") as z:
    z.extractall("../data")

### Exploring the dataset.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../data/diamonds.csv")

In [3]:
# rows, columns
print(df.shape)

# first rows
print(df.head())

# data types:
print(df.dtypes)

(53940, 11)
   Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35

      z
0  2.43
1  2.31
2  2.31
3  2.63
4  2.75
Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

In [4]:
# removing the unnamed column.
 #first make a copy t work on.
df_clean = df.copy()
if "Unnamed: 0" in df_clean.columns:
    df_clean = df_clean.drop("Unnamed: 0", axis = 1)

In [5]:
df_clean.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

### Removing the dublicated lines:

In [6]:
df_clean = df_clean.drop_duplicates()
df_clean.shape

(53794, 10)

In [7]:
print(df_clean.isna().sum())
print(""" 
""")

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [8]:
# Chaning x, y, z names
names = { "x": "length", "y": "width", "z": "depth_mm"}

df_clean = df_clean.rename(names, axis = 1)

In [9]:
df_clean.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'length',
       'width', 'depth_mm'],
      dtype='object')

In [10]:
df_clean

,carat,cut,color,clarity,depth,table,price,length,width,depth_mm
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

- **catagorical variables:** cut, color, clarity.
- **numerical variables:** carat, depth, table, price, length, width, depth_mm.

In [11]:
# unique values of catagorical variables:
print(df_clean["cut"].unique())
print(df_clean["color"].unique())
print(df_clean["clarity"].unique())

['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
['E' 'I' 'J' 'H' 'F' 'G' 'D']
['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']

In [12]:
df_clean

,carat,cut,color,clarity,depth,table,price,length,width,depth_mm
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [13]:
for column in df_clean.columns:
    if df_clean[column].dtypes != object:
        print(column, (df_clean[column] == 0).sum()) 
    pass

carat 0
depth 0
table 0
price 0
length 7
width 6
depth_mm 19

In [14]:
print(df_clean[df_clean["length"] == 0]) 
print(df_clean[df_clean["width"] == 0]) 
print(df_clean[df_clean["depth_mm"] == 0])

       carat        cut color clarity  depth  table  price  length  width  \
11182   1.07      Ideal     F     SI2   61.6   56.0   4954     0.0   6.62
11963   1.00  Very Good     H     VS2   63.3   53.0   5139     0.0   0.00
15951   1.14       Fair     G     VS1   57.5   67.0   6381     0.0   0.00
24520   1.56      Ideal     G     VS2   62.2   54.0  12800     0.0   0.00
26243   1.20    Premium     D    VVS1   62.1   59.0  15686     0.0   0.00
27429   2.25    Premium     H     SI2   62.8   59.0  18034     0.0   0.00
49556   0.71       Good     F     SI2   64.1   60.0   2130     0.0   0.00

       depth_mm
11182       0.0
11963       0.0
15951       0.0
24520       0.0
26243       0.0
27429       0.0
49556       0.0
       carat        cut color clarity  depth  table  price  length  width  \
11963   1.00  Very Good     H     VS2   63.3   53.0   5139     0.0    0.0
15951   1.14       Fair     G     VS1   57.5   67.0   6381     0.0    0.0
24520   1.56      Ideal     G     VS2   62.2   54.0  12800     0.0    0.0
26243   1.20    Premium     D    VVS1   62.1   59.0  15686     0.0    0.0
27429   2.25    Premium     H     SI2   62.8   59.0  18034     0.0    0.0
49556   0.71       Good     F     SI2   64.1   60.0   2130     0.0    0.0

       depth_mm
11963       0.0
15951       0.0
24520       0.0
26243       0.0
27429       0.0
49556       0.0
       carat        cut color clarity  depth  table  price  length  width  \
2207    1.00    Premium     G     SI2   59.1   59.0   3142    6.55   6.48
2314    1.01    Premium     H      I1   58.1   59.0   3167    6.66   6.60
4791    1.10    Premium     G     SI2   63.0   59.0   3696    6.50   6.47
5471    1.01    Premium     F     SI2   59.2   58.0   3837    6.50   6.47
10167   1.50       Good     G      I1   64.0   61.0   4731    7.15   7.04
11182   1.07      Ideal     F     SI2   61.6   56.0   4954    0.00   6.62
11963   1.00  Very Good     H     VS2   63.3   53.0   5139    0.00   0.00
13601   1.15      Ideal     G     VS2   59.2   56.0   5564    6.88   6.83
15951   1.14       Fair     G     VS1   57.5   67.0   6381    0.00   0.00
24394   2.18    Premium     H     SI2   59.4   61.0  12631    8.49   8.45
24520   1.56      Ideal     G     VS2   62.2   54.0  12800    0.00   0.00
26123   2.25    Premium     I     SI1   61.3   58.0  15397    8.52   8.42
26243   1.20    Premium     D    VVS1   62.1   59.0  15686    0.00   0.00
27112   2.20    Premium     H     SI1   61.2   59.0  17265    8.42   8.37
27429   2.25    Premium     H     SI2   62.8   59.0  18034    0.00   0.00
27503   2.02    Premium     H     VS2   62.7   53.0  18207    8.02   7.95
27739   2.80       Good     G     SI2   63.8   58.0  18788    8.90   8.85
49556   0.71       Good     F     SI2   64.1   60.0   2130    0.00   0.00
51506   1.12    Premium     G      I1   60.4   59.0   2383    6.71   6.67

       depth_mm
2207        0.0
2314        0.0
4791        0.0
5471        0.0
10167       0.0
11182       0.0
11963       0.0
13601       0.0
15951       0.0
24394       0.0
24520       0.0
26123       0.0
26243       0.0
27112       0.0
27429       0.0
27503       0.0
27739       0.0
49556       0.0
51506       0.0

In [15]:
dc = df_clean[(df_clean["width"] == 0) & (df_clean["length"] == 0) & (df_clean["depth_mm"] == 0)]
print(dc.shape)

(6, 10)

In [16]:
df_clean = df_clean.drop(dc.index, axis = 0)

In [17]:
df_clean.shape

(53788, 10)

In [18]:
for column in df_clean.columns:
    if df_clean[column].dtypes != object:
        print(column, (df_clean[column] == 0).sum()) 
    pass

carat 0
depth 0
table 0
price 0
length 1
width 0
depth_mm 13

In [19]:
dc = df_clean[(df_clean["length"] == 0) | (df_clean["depth_mm"] == 0)]
dc.shape

(13, 10)

In [20]:
# droping these rows which contain zero in either length or depth_mm.
df_clean = df_clean.drop(dc.index, axis = 0) 
df_clean.shape

(53775, 10)

In [21]:
# second method:
df_clean = df_clean[~(df_clean["length"] == 0) | (df_clean["depth_mm"] == 0)]
df_clean.shape

(53775, 10)

### Detecting and Droping outliers:

In [22]:
# detecting the outliers:
def the_outlier():
    d = [] 
    for column in df_clean.columns:
        if df_clean[column].dtype != object:
            Q1 = df_clean[column].quantile(0.25)
            Q3 = df_clean[column].quantile(0.75) 
            IQR = Q3 - Q1 
            Lower_bound = Q1 - 1.5 * IQR
            Upper_bound = Q3 + 1.5 * IQR 
            outlier = df_clean[(df_clean[column] < Lower_bound) | (df_clean[column] > Upper_bound)]
            d.append((column, len(outlier)))
    return d
the_outlier()

[('carat', 1867),
 ('depth', 2523),
 ('table', 603),
 ('price', 3520),
 ('length', 24),
 ('width', 22),
 ('depth_mm', 29)]

In [23]:
# detecting the outliers:
def the_outlier():
    d = [] 
    for column in df_clean.columns:
        if df_clean[column].dtype != object:
            Q1 = df_clean[column].quantile(0.25)
            Q3 = df_clean[column].quantile(0.75) 
            IQR = Q3 - Q1 
            Lower_bound = Q1 - 1.5 * IQR
            Upper_bound = Q3 + 1.5 * IQR 
            outlier = df_clean[(df_clean[column] < Lower_bound) | (df_clean[column] > Upper_bound)]
            
            d.append(( column, outlier[column].max(), outlier[column].min())) 
    return outlier
the_outlier()

,carat,cut,color,clarity,depth,table,price,length,width,depth_mm
14635,1.07,Ideal,F,SI1,60.6,57.0,5909,6.62,6.67,1.07
16283,3.00,Very Good,H,I1,63.1,55.0,6512,9.23,9.10,5.77
17196,2.72,Fair,J,I1,68.2,56.0,6870,8.46,8.43,5.76
19346,3.00,Fair,H,I1,67.1,57.0,8044,8.93,8.84,5.97
21758,3.11,Fair,J,I1,65.9,57.0,9823,9.15,9.02,5.98
21862,3.01,Premium,F,I1,62.2,56.0,9925,9.24,9.13,5.73
22540,3.02,Fair,I,I1,65.2,56.0,10577,9.11,9.02,5.91
23539,3.00,Good,E,I1,64.2,65.0,11548,9.08,8.96,5.79
23644,3.65,Fair,H,I1,67.1,53.0,11668,9.53,9.48,6.38
24067,2.00,Premium,H,SI2,58.9,57.0,12210,8.09,58.90,8.06
24131,3.24,Premium,H,I1,62.1,58.0,12300,9.44,9.40,5.85
24297,3.22,Ideal,I,I1,62.6,55.0,12545,9.49,9.42,5.92
24328,3.50,Ideal,H,I1,62.8,57.0,12587,9.65,9.59,6.03
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
26100,3.04,Very Good,I,SI2,63.2,59.0,15354,9.14,9.07,5.75
26194,2.01,Fair,G,SI2,65.6,56.0,15562,7.89,7.84,6.16
26431,3.40,Fair,D,I1,66.8,52.0,15964,9.42,9.34,6.27
26444,4.00,Very Good,I,I1,63.3,58.0,15984,10.01,9.94,6.31
26534,3.67,Premium,I,I1,62.4,56.0,16193,9.86,9.81,6.13
26744,3.01,Ideal,J,I1,65.4,60.0,16538,8.99,8.93,5.86
26933,3.00,Fair,I,SI2,64.8,59.0,16970,8.93,8.73,5.72
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98
27515,3.01,Fair,I,SI2,65.8,56.0,18242,8.99,8.94,5.90
27517,3.01,Good,I,SI2,63.9,60.0,18242,9.06,9.01,5.77
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72
27679,3.51,Premium,J,VS2,62.5,59.0,18701,9.66,9.63,6.03
48410,0.51,Very Good,E,VS1,61.8,54.7,1970,5.12,5.15,31.80

In [24]:
outliers = the_outlier()
outliers["table"]   # actual rows flagged for depth

14635    57.0
16283    55.0
17196    56.0
19346    57.0
21758    57.0
21862    56.0
22540    56.0
23539    65.0
23644    53.0
24067    57.0
24131    58.0
24297    55.0
24328    57.0
25998    61.0
25999    62.0
26100    59.0
26194    56.0
26431    52.0
26444    58.0
26534    56.0
26744    60.0
26933    59.0
27130    61.0
27415    59.0
27515    56.0
27517    60.0
27630    58.0
27679    59.0
48410    54.7
Name: table, dtype: float64

In [25]:
df_clean = df_clean[((df_clean["table"] >= 50) & (df_clean["table"] <= 70)) & ((df_clean["depth"] >= 52) & (df_clean["depth"] <= 72))]
df_clean["table"]
df_clean["depth"]

0        61.5
1        59.8
2        56.9
3        62.4
4        63.3
         ...
53935    60.8
53936    63.1
53937    62.8
53938    61.0
53939    62.2
Name: depth, Length: 53755, dtype: float64

In [26]:
df_clean = df_clean[((df_clean["table"] >= 50) & (df_clean["table"] <= 70)) & ((df_clean["depth"] >= 52) & (df_clean["depth"] <= 72))]  
df_clean["table"]
df_clean[["table", "depth"]].agg(["max", "min"])

     table  depth
max   70.0   71.8
min   50.0   52.2

In [27]:
df_clean.dtypes

carat       float64
cut          object
color        object
clarity      object
depth       float64
table       float64
price         int64
length      float64
width       float64
depth_mm    float64
dtype: object

In [28]:
objects = []
ints = []
for column in df_clean.columns:
    if df_clean[column].dtype == object:
        objects.append(column) 
    else:
        ints.append(column)

print("object:", objects) 
print("int", ints)

object: ['cut', 'color', 'clarity']
int ['carat', 'depth', 'table', 'price', 'length', 'width', 'depth_mm']

In [29]:
objects = {}
ints = {}
for column in df_clean.columns:
    if df_clean[column].dtype == object:
        objects[column] = df_clean[column].dtype 
    else:
        ints[column] = df_clean[column].dtype 

print(objects) 
print(ints)

{'cut': dtype('O'), 'color': dtype('O'), 'clarity': dtype('O')}
{'carat': dtype('float64'), 'depth': dtype('float64'), 'table': dtype('float64'), 'price': dtype('int64'), 'length': dtype('float64'), 'width': dtype('float64'), 'depth_mm': dtype('float64')}

In [30]:
print(df["cut"].unique())
print(df["color"].unique())
print(df_clean["clarity"].unique())

['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
['E' 'I' 'J' 'H' 'F' 'G' 'D']
['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']

In [31]:
cut_order = {"Fair": 0, "Good": 1, "Very Good": 2, "Premium": 3, "Ideal": 4}
color_order = {"J" : 0, "I" : 1, "H" : 2, "G" : 3, "F" : 4, "E" : 5, "D" : 6}
clarity_order = {
    "I1": 0,
    "SI2": 1,
    "SI1": 2,
    "VS2": 3,
    "VS1": 4,
    "VVS2": 5,
    "VVS1": 6,
    "IF": 7
}

df_clean["cut_order"] = df_clean["cut"].map(cut_order)
df_clean["color_order"] = df_clean["color"].map(color_order)
df_clean["clarity_order"] = df_clean["clarity"].map(clarity_order)

,carat,cut,color,clarity,depth,table,price,length,width,depth_mm,cut_order,color_order,clarity_order
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,4,5,1
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,3,5,2
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,1,5,4
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,3,1,3
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,4,6,2
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,1,6,2
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,2,6,2
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,3,2,1
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,4,6,1

### Correlation analysis:

- Response variable (what you're explaining): price
- Explanatory variables (what might explain it): carat, depth, table, length, width, depth_mm cut_order, color_order, clarity_order

In [33]:
df_clean[["price",
        "carat",
        "depth", 
        "table", 
        "length", 
        "width", 
        "depth_mm", 
        "cut_order", 
        "color_order", 
        "clarity_order"]].corr()

,price,carat,depth,table,length,width,depth_mm,cut_order,color_order,clarity_order
price,1.000000,0.921578,-0.010694,0.127107,0.887163,0.867690,0.868138,-0.052455,-0.171741,-0.146197
carat,0.921578,1.000000,0.028599,0.181791,0.977864,0.953984,0.961075,-0.133393,-0.290894,-0.352216
depth,-0.010694,0.028599,1.000000,-0.303292,-0.024710,-0.028788,0.095277,-0.219078,-0.048769,-0.067026
table,0.127107,0.181791,-0.303292,1.000000,0.196235,0.184628,0.152356,-0.434453,-0.026774,-0.160613
length,0.887163,0.977864,-0.024710,0.196235,1.000000,0.974819,0.975453,-0.124817,-0.270150,-0.372372
width,0.867690,0.953984,-0.028788,0.184628,0.974819,1.000000,0.956691,-0.120892,-0.263393,-0.358528
depth_mm,0.868138,0.961075,0.095277,0.152356,0.975453,0.956691,1.000000,-0.149002,-0.269514,-0.369625
cut_order,-0.052455,-0.133393,-0.219078,-0.434453,-0.124817,-0.120892,-0.149002,1.000000,0.020197,0.188219
color_order,-0.171741,-0.290894,-0.048769,-0.026774,-0.270150,-0.263393,-0.269514,0.020197,1.000000,-0.025718
clarity_order,-0.146197,-0.352216,-0.067026,-0.160613,-0.372372,-0.358528,-0.369625,0.188219,-0.025718,1.000000