# Project 1:
## Diamonds Project.

### Uploading the Dataset.

In [183]:
# unzip the file.
from zipfile import ZipFile
with ZipFile("../data/Diamond.zip", "r") as z:
    z.extractall("../data")

### Exploring the dataset.

In [184]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../data/diamonds.csv")

In [185]:
# rows, columns
print(df.shape)

# first rows
print(df.head())

# data types:
print(df.dtypes)

(53940, 11)
   Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35

      z
0  2.43
1  2.31
2  2.31
3  2.63
4  2.75
Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

In [186]:
# removing the unnamed column.
 #first make a copy t work on.
df_clean = df.copy()
if "Unnamed: 0" in df_clean.columns:
    df_clean = df_clean.drop("Unnamed: 0", axis = 1)

In [187]:
df_clean.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

### Removing the dublicated lines:

In [188]:
df_clean = df_clean.drop_duplicates()
df_clean.shape

(53794, 10)

In [189]:
print(df_clean.isna().sum())
print(""" 
""")

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [190]:
# Chaning x, y, z names
names = { "x": "length", "y": "width", "z": "depth_mm"}

df_clean = df_clean.rename(names, axis = 1)

In [191]:
df_clean.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'length',
       'width', 'depth_mm'],
      dtype='object')

In [192]:
df_clean

,carat,cut,color,clarity,depth,table,price,length,width,depth_mm
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

- **catagorical variables:** cut, color, clarity.
- **numerical variables:** carat, depth, table, price, length, width, depth_mm.

In [193]:
# unique values of catagorical variables:
print(df_clean["cut"].unique())
print(df_clean["color"].unique())
print(df_clean["clarity"].unique())

['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
['E' 'I' 'J' 'H' 'F' 'G' 'D']
['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']

In [194]:
df_clean

,carat,cut,color,clarity,depth,table,price,length,width,depth_mm
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [195]:
for column in df_clean.columns:
    if df_clean[column].dtypes != object:
        print(column, (df_clean[column] == 0).sum()) 
    pass

carat 0
depth 0
table 0
price 0
length 7
width 6
depth_mm 19

In [196]:
print(df_clean[df_clean["length"] == 0]) 
print(df_clean[df_clean["width"] == 0]) 
print(df_clean[df_clean["depth_mm"] == 0])

       carat        cut color clarity  depth  table  price  length  width  \
11182   1.07      Ideal     F     SI2   61.6   56.0   4954     0.0   6.62
11963   1.00  Very Good     H     VS2   63.3   53.0   5139     0.0   0.00
15951   1.14       Fair     G     VS1   57.5   67.0   6381     0.0   0.00
24520   1.56      Ideal     G     VS2   62.2   54.0  12800     0.0   0.00
26243   1.20    Premium     D    VVS1   62.1   59.0  15686     0.0   0.00
27429   2.25    Premium     H     SI2   62.8   59.0  18034     0.0   0.00
49556   0.71       Good     F     SI2   64.1   60.0   2130     0.0   0.00

       depth_mm
11182       0.0
11963       0.0
15951       0.0
24520       0.0
26243       0.0
27429       0.0
49556       0.0
       carat        cut color clarity  depth  table  price  length  width  \
11963   1.00  Very Good     H     VS2   63.3   53.0   5139     0.0    0.0
15951   1.14       Fair     G     VS1   57.5   67.0   6381     0.0    0.0
24520   1.56      Ideal     G     VS2   62.2   54.0  12800     0.0    0.0
26243   1.20    Premium     D    VVS1   62.1   59.0  15686     0.0    0.0
27429   2.25    Premium     H     SI2   62.8   59.0  18034     0.0    0.0
49556   0.71       Good     F     SI2   64.1   60.0   2130     0.0    0.0

       depth_mm
11963       0.0
15951       0.0
24520       0.0
26243       0.0
27429       0.0
49556       0.0
       carat        cut color clarity  depth  table  price  length  width  \
2207    1.00    Premium     G     SI2   59.1   59.0   3142    6.55   6.48
2314    1.01    Premium     H      I1   58.1   59.0   3167    6.66   6.60
4791    1.10    Premium     G     SI2   63.0   59.0   3696    6.50   6.47
5471    1.01    Premium     F     SI2   59.2   58.0   3837    6.50   6.47
10167   1.50       Good     G      I1   64.0   61.0   4731    7.15   7.04
11182   1.07      Ideal     F     SI2   61.6   56.0   4954    0.00   6.62
11963   1.00  Very Good     H     VS2   63.3   53.0   5139    0.00   0.00
13601   1.15      Ideal     G     VS2   59.2   56.0   5564    6.88   6.83
15951   1.14       Fair     G     VS1   57.5   67.0   6381    0.00   0.00
24394   2.18    Premium     H     SI2   59.4   61.0  12631    8.49   8.45
24520   1.56      Ideal     G     VS2   62.2   54.0  12800    0.00   0.00
26123   2.25    Premium     I     SI1   61.3   58.0  15397    8.52   8.42
26243   1.20    Premium     D    VVS1   62.1   59.0  15686    0.00   0.00
27112   2.20    Premium     H     SI1   61.2   59.0  17265    8.42   8.37
27429   2.25    Premium     H     SI2   62.8   59.0  18034    0.00   0.00
27503   2.02    Premium     H     VS2   62.7   53.0  18207    8.02   7.95
27739   2.80       Good     G     SI2   63.8   58.0  18788    8.90   8.85
49556   0.71       Good     F     SI2   64.1   60.0   2130    0.00   0.00
51506   1.12    Premium     G      I1   60.4   59.0   2383    6.71   6.67

       depth_mm
2207        0.0
2314        0.0
4791        0.0
5471        0.0
10167       0.0
11182       0.0
11963       0.0
13601       0.0
15951       0.0
24394       0.0
24520       0.0
26123       0.0
26243       0.0
27112       0.0
27429       0.0
27503       0.0
27739       0.0
49556       0.0
51506       0.0

In [197]:
dc = df_clean[(df_clean["width"] == 0) & (df_clean["length"] == 0) & (df_clean["depth_mm"] == 0)]
print(dc.shape)

(6, 10)

In [198]:
df_clean = df_clean.drop(dc.index, axis = 0)

In [199]:
df_clean.shape

(53788, 10)

In [200]:
for column in df_clean.columns:
    if df_clean[column].dtypes != object:
        print(column, (df_clean[column] == 0).sum()) 
    pass

carat 0
depth 0
table 0
price 0
length 1
width 0
depth_mm 13

In [201]:
dc = df_clean[(df_clean["length"] == 0) | (df_clean["depth_mm"] == 0)]
dc.shape

(13, 10)

In [202]:
# droping these rows which contain zero in either length or depth_mm.
df_clean = df_clean.drop(dc.index, axis = 0) 
df_clean.shape

(53775, 10)

In [203]:
# second method:
df_clean = df_clean[~(df_clean["length"] == 0) | (df_clean["depth_mm"] == 0)]
df_clean.shape

(53775, 10)

### Detecting and Droping outliers:

In [204]:
# detecting the outliers:
for column in df_clean.columns:
    if df_clean[column].dtype != object:
        Q1 = df_clean[column].quantile(0.25)
        Q3 = df_clean[column].quantile(0.75) 
        IQR = Q3 - Q1 
        Lower_bound = Q1 - 1.5 * IQR
        Upper_bound = Q3 - 1.5 * IQR 
        outlier = df_clean[(df_clean[column] < Lower_bound) | (df_clean[column] > Upper_bound)]
        print(column, len(outlier))

carat 53775
depth 48505
table 50307
price 53775
length 53768
width 53761
depth_mm 53741