In [2]:
import numpy as np
import pandas as pd

In [4]:
my_list = [10, 28, 7, 9]

x = np.array(my_list) 
print(x)

[10 28  7  9]

In [5]:
x

array([10, 28,  7,  9])

In [6]:
type(x)

numpy.ndarray

In [ ]:
# by default: pd.Series(data = my_list, index = ...)

y = pd.Series(my_list)
y

0    10
1    28
2     7
3     9
dtype: int64

In [10]:
type(y)

pandas.Series

In [14]:
index_values = ["best", "second best", "third best"]
my_list = [90, 65, 35]

one =pd.Series(index = index_values , data = my_list)
one

best           90
second best    65
third best     35
dtype: int64

In [17]:
index_values2 = ["best", "second best", "forth best"]
my_list2 = [90, 65, 35]

two =pd.Series(index = index_values2 , data = my_list2)
two

best           90
second best    65
forth best     35
dtype: int64

In [21]:
total = one + two
total

best           180.0
forth best       NaN
second best    130.0
third best       NaN
dtype: float64

In [24]:
pd.DataFrame({"Serie 1" : one, "Serie 2" : two})

             Serie 1  Serie 2
best            90.0     90.0
forth best       NaN     35.0
second best     65.0     65.0
third best      35.0      NaN

In [28]:
ice_cream = [["MCC", 1], ["Butterscotch", 2], ["Butter Pecan", 3]]
pd.DataFrame(ice_cream, index = ["Flavor 1", "Flavor 2", "Flavor 3"], columns = ["Flavor", "Scoop"])

                Flavor  Scoop
Flavor 1           MCC      1
Flavor 2  Butterscotch      2
Flavor 3  Butter Pecan      3